# Title:  
#    No cyclical definitions
# Constraint Description:  
#    No class definition should be self-referential. 
# Severity:  
#    Error

SELECT DISTINCT ?element ?definition ?error
WHERE {
  ?element skos:definition ?definition .
  BIND(REPLACE(?definition, "^A (wordPattern) is a *.", "$1") AS ?term)
  BIND(REPLACE(?definition, "^A (wordPattern) is a (text))", "$2") AS ?definitionWords)
  FILTER regex(?definitionWords, ?term)
  BIND (concat("Error: The following ontology element has a self-referential skos:definition ", str(?element)) AS ?error)
}
ORDER BY DESC(UCASE(str(?definition)))


