# Title:  
#    Class SubClassOf Hierarchy Circularity
# Constraint Description:  
#    No class should appear in a circular `subClassOf` hierarchy.
# Severity:  
#    Error
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?element3
WHERE {
  ?element2 rdfs:subClassOf ?element1 .
  ?element3 rdfs:subClassof* ?element2 .
  FILTER (?element3 = ?element1)
  BIND (concat("Error: The following ontology element appears in a circular `subClassOf` hierarchy ", str(?element1)) AS ?error)
}
ORDER BY DESC(UCASE(str(?element1)))